In [1]:
import numpy as np

## numpy.empty(shape,dtype=float,order='C')

In [3]:
a=np.empty([2,2],dtype=int,order="C")#c=row major,F=column major

In [4]:
a

array([[        0,         0],
       [169573600,       520]])

## Indentity matrix

In [6]:
np.eye(4)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [7]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [8]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## np.ones

In [17]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
np.ones(6)*2

array([2., 2., 2., 2., 2., 2.])

## np.zeros

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((5,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## np.arange

In [20]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
np.arange(1,24,2).reshape(3,4)#reshape(rows,columns)


array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

## np.linspace

In [27]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [29]:
np.linspace(0,1,10,endpoint=False,retstep=True)#for find steps

(array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]), 0.1)

## other properties

In [32]:
x= np.arange(1,10).reshape(3,3)

In [33]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.diag(x)

array([1, 5, 9])

In [35]:
np.diag(x,k=1)

array([2, 6])

In [36]:
np.diag(np.diag(x))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [38]:
x.sum()#sum of all the values

45

In [42]:
x.sum(axis=0)#sum of cloumns

array([12, 15, 18])

In [43]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])